/*
 * Given two strings s and t which consist of only lowercase letters.

 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 */

class Solution {
    char findTheDifference(String s, String t) {
        int[] chars = new int[26];
        for(int i = 0; i < s.length(); i++) {
            chars[s.charAt[i] - 'a']++;
        }
        for(int j = 0; j < t.length(); j++) {
            chars[t.charAt[j] - 'a']--;
        }
        for(int i = 0; i < 26; i++) {
            if(chars[i] != 0) {
                return (char) ('a' + i);
            }
        }
        return '0';
    }
};

// 数组中其余元素出现了两次，找出数组中只出现了一次的那个数字。完完全全一样的题目。方法是异或运算。

class Solution_1 {
public:
    char FindTheDifference(String s, String t) {
        int answer = 0;
        for(int i = 0; i < s.length(); i++) {
            answer ^= s.charAt(i) - 'a';
        }
        for(int j = 0; j < t.length(); j++) {
            answer ^= t.charAt(i) - 'a';
        }
        return (char) ('a' + answer);
    }
};
